### ISSUE TITLE
2.1 Review Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#101]
### Issue Description
1. Task ID: 27
2. Task: To review all Requirements of Product
      - [x] #102  
      - [x] #103 
      - [x] #104

3. Goals: To ensure that all requirements makes sense and necessary changes, if needed, are made
4. Completion Criteria: All revision of requirements to be updated inside teams' google drive
5. Allocated Time: 9/24/2023 - 9/26/2023
6. Owner: Cheryl, Jia Jin, Jin Yuan
7. Priority: Medium

**Comment by jinyuan98** [comment]
### Issue Comment
- Review of Requirements completed
- Whatever needed to be edited has been edited and uploaded in the team's google drive
- This moderately affects the project timeline as revised Requirements allows for diagrams later to be finalised without heavy changes
- No changes will be made
- 9/24/2023 - 9/26/2023
