### ISSUE TITLE
2.1.1 Review User Interface Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#102]
### Issue Description
1. Task ID: 28
2. Task: To review User Interface Requirements (UIRs)
3. Goals: To ensure that all UIRs makes sense and necessary changes, if needed, are made
4. Completion Criteria: All revision of UIRs to be updated in M2 report inside teams' google drive
5. Allocated Time: 9/24/2023 - 9/24/2023
6. Owner: Cheryl
7. Priority: Medium

**Comment by cheryl-tc** [comment]
### Issue Comment
- Review of User Interface Requirements completed
- Whatever needed to be edited has been edited and uploaded in the team's google drive
- This moderately affects the project timeline as a revised User Interface Requirements can help all stakeholders better understand the system
- No changes will be made
- 9/24/2023 - 9/24/2023
