### ISSUE TITLE
2.1.2 Review Functional Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#103]
### Issue Description
1. Task ID: 29
2. Task: To review Functional Requirements (FRs)
3. Goals: To ensure that all FRs makes sense and necessary changes, if needed, are made
4. Completion Criteria: All revision of FRs to be updated in M2 report inside teams' google drive
5. Allocated Time: 9/25/2023 - 9/25/2023
6. Owner: Jia Jin
7. Priority: Medium

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Review of Functional Requirements completed
- Whatever needed to be edited has been edited and uploaded in the team's google drive
- This moderately affects the project timeline as revised Functional Requirements can help clarify any doubts of the product
- No changes will be made
- 9/25/2023 - 9/25/2023
