### ISSUE TITLE
2.1.3 Review Non-Functional Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#104]
### Issue Description
1. Task ID: 30
2. Task: To review Non-Functional Requirements (NFRs)
3. Goals: To ensure that all NFRs makes sense and necessary changes, if needed, are made
4. Completion Criteria: All revision of NFRs to be updated in M2 report inside teams' google drive
5. Allocated Time: 9/26/2023 - 9/26/2023
6. Owner: Jin Yuan
7. Priority: Medium

**Comment by jinyuan98** [comment]
### Issue Comment
- Review of Non-Functional Requirements completed
- Whatever needed to be edited has been edited and uploaded in the team's google drive
- This moderately affects the project timeline as revised Non-Functional Requirements allows better understanding of the product
- No changes will be made
- 9/26/2023 - 9/26/2023
