### ISSUE TITLE
2.3.1.1.1 Define Boundaries

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#105]
### Issue Description 
1. Task ID: 37
2. Task: To define the boundaries of the class diagram
3. Goals: To define the boundaries to allow other components of the class diagram to be completed 
4. Completion Criteria: Boundaries defined and created
5. Allocated Time: 9/28/2023 - 10/2/2023
6. Owner: Elizabeth
7. Priority: High

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Boundaries have been defined
- Boundaries for Class Diagram has been added to the Lucid diagram used by the team
- This heavily affects the project timeline as the Class Diagram is the overview of the product
- No more changes will be made
- 9/28/2023 - 9/29/2023
