### ISSUE TITLE
2.3.1.1.2 Define Controllers

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#106]
### Issue Description 
1. Task ID: 38
2. Task: To define the controllers of the class diagram
3. Goals: To define the controllers to allow other components of the class diagram to be completed 
4. Completion Criteria: Controllers defined and created
5. Allocated Time: 9/28/2023 - 10/2/2023
6. Owner: Jia Jin
7. Priority: High

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Controllers have been defined
- Controllers for Class Diagram has been added to the Lucid diagram used by the team
- This heavily affects the project timeline as the Class Diagram is the overview of the product
- No more changes will be made
- 9/29/2023 - 9/30/2023
