### ISSUE TITLE
2.3.1.2.1 Extract Lifeline Elements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#108]
### Issue Description 
1. Task ID: 41
2. Task: To extract the lifeline elements of the Sequence Diagram
3. Goals Extract the lifeline elements within a day to allow the rest of the sequence diagram to carry on
4. Completion Criteria: Lifeline Elements extracted
5. Allocated Time: 10/3/2023 - 10/12/2023
6. Owner: Cheryl
7. Priority: High

**Comment by cheryl-tc** [comment]
### Issue Comment
- Actors and Objects have been determined and extracted
- All lifeline elements are inserted into the Sequence Diagram in the team's google drive
- This heavily affects the project timeline as it is the first step to a Sequence Diagram
- No more changes will be made
- 10/3/2023 - 10/3/2023
