### ISSUE TITLE
2.3.1.2.2 Trace Messages

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#109]
### Issue Description 
1. Task ID: 42
2. Task: To trace messages of the Sequence Diagram back to the Class Diagram
3. Goals: To complete this task ASAP to allow for other tasks of #59 to flow smoothly
4. Completion Criteria: Message tracing completed
5. Allocated Time: 10/3/2023 - 10/12/2023
6. Owner: Elizabeth
7. Priority: High

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Messages have been traced back to the Class Diagram
- All traced messages are inserted into the Sequence Diagram in the team's google drive
- This heavily affects the project timeline as it is part of the Sequence Diagram
- No more changes will be made
- 10/4/2023 - 10/4/2023
