### ISSUE TITLE
1.1 Project Charter

### ISSUE THREAD

**Issue by ElizabethLanyl** [JIAJINSIM/INF2001-P8-2#11]
### Issue Description
1. Task ID: 01
2. Task: To do up project charter and have a better understanding of our teammates
      
      - [x] #12
      - [x] #13 
      
4. Goals: To complete the project charter and understand each members strengths and weaknesses
5. Completion Criteria: Completion and signed of Project Charter document
6. Allocated Time: 8/29/2023 - 8/30/2023
7. Owner: Everyone
8. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- Project Charter document is being filled up
- Document has been created in shared google drive folder
- This does not affect the project completion deadline
- There will not be any more changes to the task
- 8/29/2023 - 8/29/2023

**Comment by UncleHengz** [comment]
### Issue Comment
- Team has filled up and signed Project Charter Document
- Document has been uploaded to shared google drive folder
- This does not affect the project completion deadline
- There will not be any more changes to the task as all team members have filled up and sign the document.
- 8/29/2023 - 8/30/2023
