### ISSUE TITLE
2.3.1.2.3 Add Simple Messages

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#110]
### Issue Description 
1. Task ID: 43
2. Task: To add simple messages to the Sequence Diagram
3. Goals: To complete this task ASAP to allow for other tasks of #59 to flow smoothly
4. Completion Criteria: All Simple Messages completed
5. Allocated Time: 10/3/2023 - 10/12/2023
6. Owner: Jia Jin
7. Priority: High

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Simple Messages have been crafted for the Sequence Diagram 
- All simple messages are inserted into the Sequence Diagram in the team's google drive
- This heavily affects the project timeline as it is part of the Sequence Diagram
- No more changes will be made
- 10/5/2023 - 10/5/2023
