### ISSUE TITLE
2.3.1.2.4 Add Return Messages

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#111]
### Issue Description 
1. Task ID: 44
2. Task: To add return messages to the Sequence Diagram
3. Goals: To complete this task ASAP to allow for other tasks of #59 to flow smoothly
4. Completion Criteria: All Return Messages completed
5. Allocated Time: 10/3/2023 - 10/12/2023
6. Owner: Jin Yuan
7. Priority: High

**Comment by jinyuan98** [comment]
### Issue Comment
- Return Messages have been crafted for the Sequence Diagram 
- All Return messages are inserted into the Sequence Diagram in the team's google drive
- This heavily affects the project timeline as it is part of the Sequence Diagram
- No more changes will be made
- 10/6/2023 - 10/6/2023
