### ISSUE TITLE
2.3.1.3.1 Determine Components

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#113]
### Issue Description 
1. Task ID: 47
2. Task: To determine the components of the Component Diagram
3. Goals: Components determined to allow other tasks of component diagram to be done up
4. Completion Criteria: Components determined and added to the Component Diagram
5. Allocated Time: 10/12/2023 - 10/21/2023
6. Owner: Cheryl
7. Priority: High

**Comment by cheryl-tc** [comment]
### Issue Comment
- All components have been determined and drawn
- Component diagram has been created with components determined and added into the team's google drive
- This highly affects the project timeline as it is part of M2 requirements
- No more changes will be made
- 10/20/2023 - 10/20/2023
