### ISSUE TITLE
2.3.1.3.2 Add Interfaces

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#114]
### Issue Description 
1. Task ID: 48
2. Task: Add Interfaces to the component diagram
3. Goals: All interfaces completed for component diagram to be completed
4. Completion Criteria: Interfaces completed
5. Allocated Time: 10/12/2023 - 10/21/2023
6. Owner: Jin Yuan
7. Priority: High

**Comment by jinyuan98** [comment]
### Issue Comment
- All Interfaces have been added to the component diagram
- They have been added to the component diagram that is inside the team's google drive
- This heavily affects the project timeline as it is part of M2 requirements
- No more changes will be made
- 10/21/2023 - 10/21/2023
