### ISSUE TITLE
4.3.2 Detailed Design

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#116]
### Issue Description 
1. Task ID: 67
2. Task: Complete Detailed Design
3. Goals: Detailed Design completed soon to allow for M3 Report to be submitted earlier
4. Completion Criteria: Detailed Design completed and added to M3 Report
5. Allocated Time: 11/10/2023 - 11/14/2023
6. Owner: Cheryl
7. Priority: High

**Comment by cheryl-tc** [comment]
### Issue Comment
- Detailed Design has been completed and checked
- Added into the M3 report which is in team's google drive
- This heavily affects the project timeline as it is part of M3 submission requirements
- No more changes will be made
-  11/12/2023 - 11/13/2023
