### ISSUE TITLE
1.1.1 Communication Plan

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#12]
### Issue Description
1. Task ID: 02
2. Task: To establish and agree on communication within the team
3. Goals: A agreed method of communication among the team established
4. Completion Criteria: Communication channel must be up
5. Allocated Time: 8/29/2023 - 8/29/2023
6. Owner: Elizabeth
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Slack channel to be created with all members added in
- All members added into Slack channel and is able to communicate within
- This does not affect the project completion deadline
- There will not be any more changes to the task
- 8/29/2023 - 8/29/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- The Slack channel for the team has been created
- Team members along with professors added into the slack channel
- This does not affect the project completion deadline
- No more changes will be as all members are inside the channel
- 8/29/2023 - 8/29/2023
