### ISSUE TITLE
1.1.2 Role Allocation

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#13]
### Issue Description
1. Task ID: 03
2. Task: To allocate tasks to each member of the team
3. Goals: Each member to have a task delegated to them and are aware of it
4. Completion Criteria: All members are clear of their tasks for the project
5. Allocated Time: 8/30/2023 - 8/30/2023
6. Owner: Jia Jin
7. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- Delegate tasks to each member of the team
- All members are aware of their tasks to be done
- This will moderately affect the project completion deadline
- No changes
- 8/30/2023 - 8/30/2023

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Each member has been allocated a role based on the list of roles in the project charter document
- All members have selected their roles based on their own strengths & weaknesses
- This will moderately affect the project timeline as we do not necessary have to complete this before starting the project
- No changes will be made as the role allocated is just a position and the work allocated for the project will be based on the task on hand and the members can help one another out
