### ISSUE TITLE
T5.1 Client Follow Up Email 1

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#19]
### Issue Description 
1. Task Title: T06
2. Task: First follow up with client through email to clarify any doubts
3. Goal: To receive a reply from the client to verify our doubts
4. Completion Criteria: Email has been sent to client
5. Allocated Time: 9/6/2023 - 9/15/2023
6. Owner: Jin Yuan
7. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- Emailing of client so as to verify any doubts over project requirements
- Follow up email 1 has not been sent
- This will moderately affect the project completion deadline
- Changes will be made once email has been sent
- 9/6/2023 - 9/14/2023

**Comment by UncleHengz** [comment]
### Issue Comment
- Emailing of client to confirm and verify doubt over project requirements
- Follow up email 1 has been sent
- This will moderately affect the project completion deadline
- No Changes
- 9/15/2023 - 9/15/2023

**Comment by jinyuan98** [comment]
### Issue Comment
- Email to client has been sent
- Email sent to client however no reply was received
- This moderately affects the project completion deadline
- No changes as due to project timeline, a reply from the client is not needed
- 9/15/2023 - 9/15/2023
