### ISSUE TITLE
2.2 Review Use Cases

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#31]
### Issue Description
1. Task ID: 31
2. Task: To review all Use Case

      - [x] #32 
      - [x] #33 

3. Goals: To ensure that all use cases makes sense and necessary changes, if needed, are made
4. Completion Criteria: All revision of use cases to be updated inside teams' google drive
5. Allocated Time: 9/27/2023 - 9/27/2023
6. Owner: Everyone
7. Priority: Medium

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Task is currently in progress
- Discussions and minor notes taken down and is shared among the team inside the team's google drive folder
- This moderately affects the project timeline as if there are changes, it would affect how the product would function/look
- Changes will be made as it is still in progress
- 9/24/2023 - 9/24/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Task completed as issues #32 & #33 have been closed
- All updated Use Case Model and descriptions have been uploaded to the team's google drive
- This moderately affects the project timeline as if there are changes, it would affect how the product would function/look
- No More changes will be made
- 9/27/2023 - 9/27/2023
