### ISSUE TITLE
2.2.1 Review Use Case Model

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#32]
### Issue Description 
1. Task ID: 32
2. Task: To review the use case model to make changes if needed
3. Goals: Make changes for use case model to improve it 
4. Completion Criteria: Revised use case model to be inserted into team's google drive
5. Allocated Time: 9/27/2023 - 9/27/2023
6. Owner: Jia Jin
7. Priority: Medium

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Use case model review is in progress
- Nothing has been uploaded to the team's google drive, only team's comments made
- This moderately affects the project timeline as a revised use case model can help all stakeholders better understand the system
- Changes will still be made as this is in progress
- 9/27/2023 - 9/27/2023

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Review of use case model completed
- Whatever needed to be edited has been edited and uploaded in the team's google drive
- This moderately affects the project timeline as a revised use case model can help all stakeholders better understand the system
- No changes will be made
- 9/27/2023 - 9/27/2023
