### ISSUE TITLE
1.2.1.1 Product Scope

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#38]
### Issue Description 
1. Task Title: 06
2. Task: Product Scope of M1 Report
3. Goals: To write the product scope inside M1 Report
4. Completion Criteria: Product Scope written and vetted
5. Allocated Time: 8/30/2023 - 8/30/2023
6. Owner: Elizabeth
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Product Scope has already been written but not vetted
- Written in M1 report which is inside team's google drive
- This heavily affects the project as it is a submission requirement
- Changes may be made when it has been vetted by the team
- 8/30/2023 - 9/12/2023

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Product Scope has been written & vetted by the team
- It has been written in the M1 report to briefly explain the scope of the project
- This impacts the project timeline heavily as it is part of the M1 submission requirement
- No more changes will be made as it has been vetted by the team
- 9/18/2023 - 9/19/2023. There were delays to the completion of this tasks as other modules have increased our workload
