### ISSUE TITLE
1.2.2.2 Product Functionality

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#44]
### Issue Description 
1. Task ID: 12
2. Task: Product Functionality of M1 Report
3. Goals: Summary of High Level Functionalities of project
4. Completion Criteria: Summary to be completed and inserted into M1 Report
5. Allocated Time: 9/2/2023 - 9/3/2023
6. Owner: Jia Jin
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Product Functionality has been started slightly
- Nothing has been filled in M1 report but this has been discussed with the team
- This heavily affects the project timeline as it is part of the M1 submission
- Changes will be made to fill up this portion in the report
- 9/16/2023 - 9/16/2023

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Product Functionality has been completed
- It has been inputted into the M1 report inside the team's google drive
- This heavily affects the project timeline as it is a requirement for the project and submission. There is a delay with this tasks as the team has other modules workload to do.
- No more changes will be made to this task
- 9/19/2023 - 9/19/2023
