### ISSUE TITLE
1.2.2.3 Assumptions & Dependencies

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#45]
### Issue Description 
1. Task ID: 13
2. Task: Assumptions & Dependencies of project
3. Goals: Assumptions & Dependencies to be discussed and inputted into report
4. Completion Criteria: All Assumptions to be filled up in M1 report
5. Allocated Time: 9/3/2023 - 9/4/2023
6. Owner: Jin Yuan
7. Priority: Medium

**Comment by UncleHengz** [comment]
### Issue Comment
- Nothing has been written but has been discussed when doing our tasks
- This portion in M1 report has not been filled
- This moderately affects the project due to it being part of the M1 criteria
- Changes will be made once the team fills in in the M1 report document
- 9/16/2023 - 9/16/2023

**Comment by jinyuan98** [comment]
### Issue Comment
- What was discussed and confirmed has been written inside M1 report. Task has been completed
- All has been written inside M1 report which is in the team's google drive
- This moderately affects the timeline as it lays out our assumptions of the project which we did not get to confirm with the client
- No more changes will be made to this task.
- 9/20/2023 - 9/20/2023. There is a delay with the completion of this task as the team not only has other modules workload, sometimes the team has forgotten to update the Kanban board
