### ISSUE TITLE
1.2.3 Specific Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#46]
### Issue Description
1. Task ID: 14
2. Task: To lay out the requirements of the project

      - [x] #47 
      - [x] #48 
      - [x] #49 
      - [x] #50 

3. Goals: All requirements are more or less laid out for the project
4. Completion Criteria: All requirements of the project are established
5. Allocated Time: 8/30/2023 - 9/18/2023
6. Owner: Everyone
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Lay out requirements of project
- Currently in progress in a document inside the team's google drive
- This heavily affects the project completion deadline as it can affect other tasks
- There will be changes as this is currently still in progress and the team is slightly behind the set timeline
- 8/31/2023 - 9/14/2023

**Comment by cheryl-tc** [comment]
### Issue Comment
- Tasks #47, #48, #49, #50 have been completed
- All tasks completed and inserted into M1 report
- This heavily affects the project timeline as it affects other tasks
- There will be no more changes to these
- 9/22/2023 - 9/22/2023
