### ISSUE TITLE
1.2.3.2 Functional Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#48]
### Issue Description
1. Task ID: 16
2. Task: To lay out the functional requirements of the project
3. Goals: All functional requirements of the project are laid out
4. Completion Criteria: All functional requirements of the project are established
5. Allocated Time: 8/30/2023 - 9/18/2023
6. Owner: Jin Yuan
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Lay out most functional requirements of the project
- Currently in progress in a document inside the team's google drive
- This heavily affects the project completion deadline as it can affect other tasks
- There will be changes as this is currently still in progress and more might be added
- 8/31/2023 - 9/15/2023

**Comment by jinyuan98** [comment]
### Issue Comment
- All Functional Requirements of the project has been laid out
- Task has been completed and has been inputted inside the M1 report inside the team's google drive
- This heavily affects the project timeline as it is required to complete other tasks
- There will not be any more changes as these requirements have been finalised
- 9/19/2023 - 9/19/2023
