### ISSUE TITLE
1.2.3.3 Use Case Model

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#49]
### Issue Description 
1. Task ID: 17
2. Task: To do Use Case Model for the project
3. Goals: Use Case Model completed without issues
4. Completion Criteria: Use Case Model done and placed inside M1 report
5. Allocated Time: 9/6/2023 - 9/18/2023
6. Owner: Cheryl
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Use Case Model drawn
- Use Case Model has been placed inside M1 report
- This heavily affects the project timeline as it showcases the use case of the product
- Changes may be made if there is a need to do so
- 9/14/2023 - 9/16/2023

**Comment by cheryl-tc** [comment]
### Issue Comment
- Use Case Model has been completed with edits made
- Use Case Model has been inserted into the M1 report
- This heavily affects the project timeline as it is needed for the use case description to be done up
- No more changes will be made as all final edits have been inserted
- 9/19/2023 - 9/19/2023. There was a slight delay as the team wanted to clarify with our instructor on whether the model was not done wrongly.
