### ISSUE TITLE
1.2.3.4 Non-Functional Requirements

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#50]
### Issue Description
1. Task Title: 18
2. Task: To lay out the non-functional requirements of the project
      
      - [x] #51 
      - [x] #52 
      
3. Goals: Non-functional requirements is understood by everyone and agrees
4. Completion Criteria: All non-functional requirements of the project are established
5. Allocated Time: 8/30/2023 - 9/16/2023
6. Owner: Jia Jin & Jin Yuan
7. Priority: Low

**Comment by UncleHengz** [comment]
### Issue Comment
- Lay out non-functional requirements of the project
- To be done in the document inside team's google drive
- This lightly affects the project completion deadline as this is not the top priority out of all requirements
- There will be changes as this is currently still in progress and the team is slightly behind the set timeline
- 8/31/2023 - 9/14/2023

**Comment by UncleHengz** [comment]
### Issue Comment
- Some non-functional requirements have been laid out
- Currently in a separate document
- This lightly affects the project completion deadline as this is not the top priority out of all requirements
- There will still be changes as further sub-issues are not completed yet
- 9/15/2023 - 9/16/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- All non-functional requirements completed. Tasks #51 & #52 completed.
- Everything has been inputted into the M1 report inside the team's google drive
- All these lightly affect the project timeline even though they are requirements of the project too
- There will not be any more changes to these
- 9/18/2023 - 9/19/2023. There was a delay as the team was unsure on how to categorize the requirements and also other modules' workload has slightly overwhelmed the team.
