### ISSUE TITLE
1.2.5 Project Estimation & Plan

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#54]
### Issue Description 
1. Task ID: 22
2. Task: Project estimation & planning

      - [x] #55 
      - [x] #56 

3. Goals: To plan out the project with no objections from the team
4. Completion Criteria: Project Estimation & Plan & its sub-issues completed
5. Allocated Time: 8/30/2023 - 9/18/2023
6. Owner: Cheryl & Yi Heng
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Project Planning is currently still in progress
- Gantt Chart is in the team's google drive & Kanban board is in team's Github repository
- This heavily affects the project as it is the plans of the project
- Changes will be made still
- 9/14/2023 - 9/16/2023

**Comment by cheryl-tc** [comment]
### Issue Comment
- Tasks #55, #56 has been completed
- Both tasks have been inputted into M1 report inside the team's google drive
- This heavily affects the project timeline due to it covers the project planning
- No more changes will be made
- 9/22/2023 - 9/23/2023
