### ISSUE TITLE
1.2.5.1 Software Estimation

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#55]
### Issue Description 
1. Task ID: 23
2. Task: To estimate the project manpower and time required
3. Goals: Having a realistic estimation of the project
4. Completion Criteria: All estimation completed inside M1 report
5. Allocated Time: 8/30/2023 - 9/18/2023
6. Owner: Cheryl
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- Some estimation has been done but not all
- Not written in the M1 report yet
- This affects the project timeline heavily
- Changes will still be made as it is still in progress
- 9/12/2023 - 9/16/2023

**Comment by cheryl-tc** [comment]
### Issue Comment
- All software estimations have been calculated
- All calculations have been verified by the team and inserted into the M1 report inside the team's google drive
- This affects the project timeline as it is important to estimate the duration and manpower required for the project
- No more changes will be made
- 9/22/2023 - 9/23/2023. There were delays as there some confusion on the calculations.
