### ISSUE TITLE
1.2.6 Use Case Description

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#57]
### Issue Description 
1. Task ID: 25
2. Task: Use Case Description of the #49 
3. Goals: Use Case Description done up 
4. Completion Criteria: Use Case Description Completed and inputted into M1 Report
5. Allocated Time: 9/18/2023 - 9/21/2023
6. Owner: Elizabeth & Yi Heng
7. Priority: High

**Comment by UncleHengz** [comment]
### Issue Comment
- To be started on when Use Case Model has no more changes
- Will be filled up in the table inside M1 Report
- This heavily affects the project as it will affect other calculations and models for the project
- Changes will be made when this is started
- 9/16/2023 - 9/16/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Use Case Description for the Use Case Model is currently in progress
- Use Case Descriptions are being created inside the M1 report inside the team's google drive
- This heavily affects the project as it will affect the product estimation of the project
- Changes will still be made as it is currently in progress
- 9/18/2023 - 9/19/2023. There is a delay due the workload created by other modules

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Use Descriptions have been completed
- All Use Case Descriptions have been inputted into the appendix of the M1 Report inside the team's google drive folder
- This heavily affects the project as it allows the team to calculate the estimation of the project
- No more changes will be made
- 9/20/2023 - 9/20/2023
