### ISSUE TITLE
2.3.1 Software Design

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#60]
### Issue Description 
1. Task ID: 35
2. Task: To complete the 3 diagrams for the product
      
      - [x] #61  
      - [x] #59 
      - [x] #62 
      
3. Goals: All complete all 3 diagrams few days before M2 submission dateline to allow for vetting and editing within the team
4. Completion Criteria: All 3 diagrams completed by M2 submission
5. Allocated Time: 9/28/2023 - 10/22/2023
6. Owner: Everyone
7. Priority: High

**Comment by cheryl-tc** [comment]
### Issue Comment
- Diagrams are currently in progress
- A single link with all 3 diagrams have been shared inside the team's google drive
- Heavily affects the project timeline as the respective diagrams illustrates the product
- Changes will be made as tasks are still in progress
- 10/2/2023 - 10/2/2023

**Comment by jinyuan98** [comment]
### Issue Comment
- All diagrams have been completed
- All diagrams have been vetted and edited as necessary and have been added to M2 report inside the team's google drive
- This heavily affects the project timeline as they are requirements for M2 submission
- No more changes will be made
- 10/22/2023 - 10/22/2023
