### ISSUE TITLE
2.3.1.1 Class Diagram

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#61]
### Issue Description 
1. Task ID: 36
2. Task: To complete the Class Diagram of the product
      
      - [x] #105 
      - [x] #106 
      - [x] #107 
      
3. Goals: All complete class diagram together with no changes to be made last minute
4. Completion Criteria: Class Diagram done up and uploaded
5. Allocated Time: 9/28/2023 - 10/2/2023
6. Owner: Elizabeth, Jia Jin, Yi Heng
7. Priority: High

**Comment by cheryl-tc** [comment]
### Issue Comment
- Class Diagram have been done up
- Class Diagram has been copied over to the M2 report
- This heavily affects the project timeline as the Class Diagram is the overview of the product
- No more changes will be made
- 10/10/2023 - 10/14/2023

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Class Diagram have been done up
- Class Diagram has been copied over to the M2 report
- This heavily affects the project timeline as the Class Diagram is the overview of the product
- No more changes will be made
- 10/1/2023 - 10/2/2023
