### ISSUE TITLE
2.3.1.3 Component Diagram

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#62]
### Issue Description 
1. Task ID: 46
2. Task: To complete the Component Diagram of the product
      
      - [x] #113 
      - [x] #114 
      
3. Goals: All to complete sequence diagram together with no changes to be made last minute
4. Completion Criteria: Complete Diagram done up and uploaded
5. Allocated Time: 10/12/2023 - 10/21/2023
6. Owner: Cheryl & Jin Yuan
7. Priority: High

**Comment by cheryl-tc** [comment]
### Issue Comment
- Component diagram has been completed
- The component diagram has been added into the M2 report inside the team's google drive
- This highly affects the project timeline as it is a requirement for M2
- No more changes will be made
- 10/21/2023 - 10/21/2023
