### ISSUE TITLE
3.1 Web Front End Development

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#63]
### Issue Description 
1. Task ID: 49
2. Task: Have all Web Front End developed
      
      - [x] #64 
      - [x] #65 
      - [x] #66 
      - [x] #67 

3. Goals: All sub-tasks to be completed before dateline
4. Completion Criteria: Web Front End developed
5. Allocated Time: 10/30/2023 - 11/3/2023
6. Owner: Everyone
7. Priority: Medium

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Front End has been designed and implemented
- Codes have been uploaded onto the team's github
- This moderately affects the project timeline as it is required for product testing later
- No more changes will be made
- 11/3/2023 - 11/3/2023
