### ISSUE TITLE
3.1.1 Login Page

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#64]
### Issue Description 
1. Task ID: 50
2. Task: Have login page done up
3. Goals: login page completed within a day to not bottleneck the project
4. Completion Criteria: Login Page completed
5. Allocated Time: 10/30/2023 - 10/31/2023
6. Owner: Cheryl
7. Priority: Medium

**Comment by cheryl-tc** [comment]
### Issue Comment
- Login Page has been designed and implemented
- Codes have been uploaded onto the team's github
- This moderately affects the project timeline as it is required for product testing later
- No more changes will be made
- 10/30/2023 - 10/30/2023
