### ISSUE TITLE
3.1.2 Manager Page

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#65]
### Issue Description 
1. Task ID: 51
2. Task: Have manager page done up
3. Goals: manager page completed within a day to not bottleneck the project
4. Completion Criteria: Manager Page Completed
5. Allocated Time: 10/30/2023 - 11/1/2023
6. Owner: Jin Yuan
7. Priority: Medium

**Comment by jinyuan98** [comment]
### Issue Comment
- Manager Page has been designed and implemented
- Codes have been uploaded onto the team's github
- This moderately affects the project timeline as it is required for product testing later
- No more changes will be made
- 10/31/2023 - 10/31/2023
