### ISSUE TITLE
3.1.3 Staff Page

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#66]
### Issue Description 
1. Task ID: 52
2. Task: Have staff page done up
3. Goals: Staff page completed within a day to not bottleneck the project
4. Completion Criteria: Staff Page Completed
5. Allocated Time: 10/30/2023 - 11/1/2023
6. Owner: Elizabeth
7. Priority: Medium

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Staff Page has been designed and implemented
- Codes have been uploaded onto the team's github
- This moderately affects the project timeline as it is required for product testing later
- No more changes will be made
- 10/31/2023 - 10/31/2023
