### ISSUE TITLE
3.1.4 IT Administrator Page

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#67]
### Issue Description 
1. Task ID: 53
2. Task: Have IT Admin page done up
3. Goals: Admin page completed within a day to not bottleneck the project
4. Completion Criteria: Admin Page Completed
5. Allocated Time: 10/30/2023 - 11/1/2023
6. Owner: Yi Heng
7. Priority: Medium

**Comment by jinyuan98** [comment]
### Issue Comment
- IT Admin Page has been designed and implemented
- Codes have been uploaded onto the team's github
- This moderately affects the project timeline as it is required for product testing later
- No more changes will be made
- 10/30/2023 - 10/30/2023

**Comment by UncleHengz** [comment]
### Issue Comment
- IT Admin Page has been designed and implemented
- Codes have been uploaded onto the team's github
- This moderately affects the project timeline as it is required for product testing later
- No more changes will be made
- 10/30/2023 - 10/30/2023
