### ISSUE TITLE
3.2.1 Student & Staff Backend

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#69]
### Issue Description 
1. Task ID: 55
2. Task: Student & Staff Backend done up
3. Goals: Student & Staff Backend completed ASAP to push for product testing
4. Completion Criteria: Student & Staff Backend Completed
5. Allocated Time: 10/30/2023 - 11/8/2023
6. Owner: Jia Jin
7. Priority: Medium

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Staff Backend has been implemented and Student external database has been linked
- Codes have been uploaded onto the team's github
- This moderately affects the project timeline as it is required for product testing later
- No more changes will be made
- 10/31/2023 - 11/5/2023
