### ISSUE TITLE
3.4 Product Revision

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#74]
### Issue Description 
1. Task ID: 58
2. Task: Product Revision after UI/UX review
3. Goals: Make revisions to the UI/UX upon team's agreement. 
4. Completion Criteria: Product Revisions completed
5. Allocated Time: 11/11/2023 - 11/19/2023
6. Owner: Everyone
7. Priority: Low

**Comment by cheryl-tc** [comment]
### Issue Comment
- All revisions that were discussed has been made
- Code has been updated in the team's github
- This does not heavily affect the project timeline as when creating the actual product, minor changes can be done also
- No more changes will be done
- 11/18/2023 - 11/18/2023
