### ISSUE TITLE
4.1 Set Up Testing Environment

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#76]
### Issue Description 
1. Task ID: 59
2. Task: Setting Up Testing Environment
      
      - [x] #77 
      
3. Goals: Testing Environment set up within a few hours to allow the team to start other tasks earlier 
4. Completion Criteria: Testing Environment set up
5. Allocated Time: 11/9/2023 - 11/9/2023
6. Owner: Cheryl, Elizabeth
7. Priority: Medium

**Comment by cheryl-tc** [comment]
### Issue Comment
 - Testing Environment has been set up
 - All information is inside team's google drive
 - This moderately affects the project timeline as testing is required for the project
 - No more changes will be made
 - 11/9/2023 - 11/9/2023
