### ISSUE TITLE
4.1.1 Generation of Test Cases

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#77]
### Issue Description 
1. Task ID: 60
2. Task: Generate test cases for testing environment
3. Goals: Test Cases generated within a few hours to allow other tasks to begin sooner
4. Completion Criteria: Test Cases generated
5. Allocated Time: 11/9/2023 - 11/9/2023
6. Owner: Elizabeth
7. Priority: Medium

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Test Cases generated for use in testing environment
- Generated test cases have been uploaded to the team's google drive
- This moderately affects the project timeline as it can help with the testing phase
- There will not be any more changes made
- 11/9/2023 - 11/9/2023
