### ISSUE TITLE
4.2 Front-End Testing

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#78]
### Issue Description 
1. Task ID: 61
2. Task: Conduct Front-End Testing
      
      - [x] #79 
      - [x] #80 
      - [x] #81 
      
3. Goals: Front-End Testing completed soon to allow for actual deployment
4. Completion Criteria: Front-End Testing completed
5. Allocated Time: 11/10/2023 - 11/10/2023
6. Owner: Elizabeth, Yi Heng
7. Priority: Medium

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Front-End Testing conducted
- Required changes to codes have been made and updated in team's github
- This moderately affects the project timeline as it is essential to test the UI
- No more changes will be made
- 11/10/2023 - 11/10/2023
