### ISSUE TITLE
4.2.2 Responsiveness

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#80]
### Issue Description 
1. Task ID: 63
2. Task: Conduct Responsiveness Testing
3. Goals: Complete Responsiveness Testing fast to allow Product Deployment to begin earlier
4. Completion Criteria: Responsiveness Testing completed
5. Allocated Time: 11/10/2023 - 11/10/2023
6. Owner: Elizabeth
7. Priority: Medium

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Responsiveness Testing conducted
- Required changes to code have been made and updated in team's github
- This moderately affects the project timeline as it is essential to test the UI
- No more changes will be made
- 11/10/2023 - 11/10/2023
