### ISSUE TITLE
4.3.3 Back-End Testing

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#82]
### Issue Description 
1. Task ID: 68
2. Task: To Plan & Conduct Back-End Testing

      - [x] #83 
      - [x] #84 
      
3. Goals: Back-End Testing completed soon to allow for M3 Submission
4. Completion Criteria: Back-End Testing planned and completed
5. Allocated Time: 11/10/2023 - 11/19/2023
6. Owner: Jia Jin, Jin Yuan
7. Priority: High

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Back-End Testing has been planned and conducted
- All required documentation has been added to M3 report inside team's google drive
- This heavily affects the project timeline as it is a requirement for M3 submission
- No more changes will be made
- 11/19/2023 - 11/19/2023
