### ISSUE TITLE
4.3.3.1 Black-Box Testing

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#83]
### Issue Description 
1. Task ID: 69
2. Task: Complete and plan Black-Box Testing    
3. Goals: Black-Box Testing completed soon to allow for M3 submission earlier
4. Completion Criteria: Black-Box Testing planned and conducted
5. Allocated Time: 11/10/2023 - 11/19/2023
6. Owner: Jia Jin
7. Priority: High

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Black-Box Testing Planned and Tested
- All documentation required is inside the M3 report in the team's google drive
- This heavily affects the project timeline as this is a requirement for M3 submission
- No more changes will be made
- 11/18/2023 - 11/18/2023
