### ISSUE TITLE
4.3.3.2 White-Box Testing

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#84]
### Issue Description 
1. Task ID: 70
2. Task: Complete and plan White-Box Testing    
3. Goals: White-Box Testing completed soon to allow for M3 submission earlier
4. Completion Criteria: White-Box Testing planned and conducted
5. Allocated Time: 11/10/2023 - 11/19/2023
6. Owner: Jin Yuan
7. Priority: High

**Comment by jinyuan98** [comment]
### Issue Comment
- White-Box Testing Planned and Tested
- All documentation required is inside the M3 report in the team's google drive
- This heavily affects the project timeline as this is a requirement for M3 submission
- No more changes will be made
- 11/18/2023 - 11/18/2023
