### ISSUE TITLE
4.3.4 Documentation of Test Results

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#85]
### Issue Description 
1. Task ID: 71
2. Task: Document down the test results  
3. Goals: Test results documented soon to allow for M3 submission earlier
4. Completion Criteria: Test results documented and inputted into M3 report
5. Allocated Time: 11/15/2023 - 11/21/2023
6. Owner: Everyone
7. Priority: High

**Comment by cheryl-tc** [comment]
### Issue Comment
- Test Results have been documented
- All documentation has been added into M3 report which is in team's google drive
- This heavily affects the project timeline as it is a requirement for M3 submission
- No more changes will be made
- 11/19/2023 - 11/19/2023
