### ISSUE TITLE
4.5.1 Website Hosting

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#87]
### Issue Description 
1. Task ID: 74
2. Task: To host website on a cloud server
3. Goals: Host website on cloud server smoothly to allow for a smooth product deployment
4. Completion Criteria: Host website on cloud server and inform the team
5. Allocated Time: 11/20/2023 - 11/21/2023
6. Owner: Elizabeth
7. Priority: Medium

**Comment by ElizabethLanyl** [comment]
### Issue Comment
- Website is hosted on AWS
- Login credentials have been shared inside team's google drive
- This moderately affects the project timeline due to this being a requirement for the product deployment
- No more changes will be made
- 11/21/2023 - 11/21/2023
