### ISSUE TITLE
4.6 Product Deployment

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#89]
### Issue Description 
1. Task ID: 76
2. Task: Deploy product to allow clients to use
      
      - [x] #90 
      
3. Goals: Product Deployment with no hiccups
4. Completion Criteria: Product Deployed and documentation taken down
5. Allocated Time: 11/21/2023 - 11/24/2023
6. Owner: Jia Jin
7. Priority: Medium

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Product Deployment has been completed
- All relevant details and documentation has been handed over to the client
- This moderately affects the project timeline as the client has to know about the details of the project 
- No more changes will be made
- 11/23/2023 - 11/23/2023
