### ISSUE TITLE
4.6.1 Documentation of Product Deployment

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#90]
### Issue Description 
1. Task ID: 77
2. Task: Document product deployment
3. Goals: Product Deployment documentation done proper
4. Completion Criteria: Product Product deployment documented and stored in team's google drive
5. Allocated Time: 11/21/2023 - 11/24/2023
6. Owner: Jia Jin
7. Priority: Medium

**Comment by JIAJINSIM** [comment]
### Issue Comment
- All product deployment documentation has been completed
- All documentation is uploaded into the team's google drive
- This moderately affects the project timeline as documentation is important for any handover
- No more changes will be made
- 11/23/2023 - 11/23/2023
