### ISSUE TITLE
4.3.5 Prototype Deployment

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#92]
### Issue Description 
1. Task ID: 72
2. Task: Create Prototype and deploy it 
3. Goals: Prototype created soon to allow for M3 submission earlier
4. Completion Criteria: Prototype created and added into M3 report
5. Allocated Time: 11/11/2023 - 11/17/2023
6. Owner: Everyone
7. Priority: High

**Comment by JIAJINSIM** [comment]
### Issue Comment
- Prototype has been created
- Prototype has been added into team's google drive and added to M3 report
- This heavily affects the project timeline as it is a requirement of M3 report
- No more changes will be made
- 11/17/2023 - 11/17/2023
