### ISSUE TITLE
4.4 Client Review

### ISSUE THREAD

**Issue by UncleHengz** [JIAJINSIM/INF2001-P8-2#93]
### Issue Description 
1. Task ID: 73
2. Task: To have client review the prototype to allow for setting up of actual product
3. Goals: Client Review conducted ASAP to allow for changes and deployment of actual product
4. Completion Criteria: Client Review conducted with client
5. Allocated Time: 11/18/2023 - 11/20/2023
6. Owner: Cheryl
7. Priority: Medium

**Comment by cheryl-tc** [comment]
### Issue Comment
- Client Review has been conducted
- All comments and changes have been shared in team's google drive
- This moderately affects the project timeline as the client's opinion is crucial
- No more changes will be made
- 11/19/2023  - 11/19/2023
